using System.Text;
using System.Xml;
using DevTools.Core.Text;

namespace DevTools.Core.Xml;

/// <summary>Everything the XML formatter lets the caller choose.</summary>
public sealed record XmlFormatOptions
{
    public IndentStyle IndentStyle { get; init; } = IndentStyle.TwoSpaces;

    /// <summary>Drops every insignificant whitespace node and writes the document on one line.</summary>
    public bool Minify { get; init; }

    /// <summary>Puts each attribute of an element on a line of its own.</summary>
    public bool NewLineOnAttributes { get; init; }

    /// <summary>Leaves comments out of the output.</summary>
    public bool RemoveComments { get; init; }

    public static XmlFormatOptions Default { get; } = new();
}

/// <summary>The formatted document and a little about what it contained.</summary>
public sealed record XmlFormatResult(string Output, int ElementCount, int AttributeCount, int MaxDepth);

/// <summary>
/// Re-indents or minifies XML.
/// </summary>
/// <remarks>
/// <para>
/// It streams: an <see cref="XmlReader"/> feeds an <see cref="XmlWriter"/> node by node, so a
/// document is never held twice over as a DOM — DevToys loads an <c>XmlDocument</c> and saves
/// it back out, which costs several times the input in memory.
/// </para>
/// <para>
/// DTDs are read but never processed and no external entity is ever resolved, so a document
/// cannot make the formatter open a file or a URL (XXE). The XML declaration is copied through
/// exactly as written, encoding name included, rather than being regenerated by the writer.
/// </para>
/// </remarks>
public static class XmlFormatter
{
    public static OperationResult<XmlFormatResult> Format(string? xml, XmlFormatOptions? options = null)
    {
        var opts = options ?? XmlFormatOptions.Default;

        if (TextUtil.IsBlank(xml))
        {
            return OperationResult<XmlFormatResult>.Ok(new XmlFormatResult(string.Empty, 0, 0, 0));
        }

        var text = TextUtil.StripBom(xml).Trim();

        var readerSettings = new XmlReaderSettings
        {
            DtdProcessing = DtdProcessing.Ignore,
            XmlResolver = null,
            IgnoreWhitespace = true,
            IgnoreComments = opts.RemoveComments,
            CheckCharacters = false,
            ConformanceLevel = ConformanceLevel.Document,
        };

        var writerSettings = new XmlWriterSettings
        {
            OmitXmlDeclaration = true,
            Indent = !opts.Minify,
            IndentChars = TextUtil.IndentUnit(opts.IndentStyle),
            NewLineChars = "\n",
            NewLineHandling = NewLineHandling.None,
            NewLineOnAttributes = opts.NewLineOnAttributes && !opts.Minify,
            CheckCharacters = false,
            ConformanceLevel = ConformanceLevel.Document,
        };

        var body = new StringBuilder(text.Length + (text.Length / 4));
        string? declaration = null;
        var elements = 0;
        var attributes = 0;
        var maxDepth = 0;

        try
        {
            using var stringReader = new StringReader(text);
            using var reader = XmlReader.Create(stringReader, readerSettings);
            using (var writer = XmlWriter.Create(body, writerSettings))
            {
                while (reader.Read())
                {
                    switch (reader.NodeType)
                    {
                        case XmlNodeType.XmlDeclaration:
                            declaration = $"<?xml {reader.Value}?>";
                            break;

                        case XmlNodeType.Element:
                            elements++;
                            maxDepth = Math.Max(maxDepth, reader.Depth + 1);
                            attributes += reader.AttributeCount;

                            var empty = reader.IsEmptyElement;
                            writer.WriteStartElement(reader.Prefix, reader.LocalName, reader.NamespaceURI);
                            writer.WriteAttributes(reader, defattr: false);

                            if (empty)
                            {
                                writer.WriteEndElement();
                            }

                            break;

                        case XmlNodeType.EndElement:
                            writer.WriteFullEndElement();
                            break;

                        case XmlNodeType.Text:
                            writer.WriteString(reader.Value);
                            break;

                        case XmlNodeType.CDATA:
                            writer.WriteCData(reader.Value);
                            break;

                        case XmlNodeType.Comment:
                            writer.WriteComment(reader.Value);
                            break;

                        case XmlNodeType.ProcessingInstruction:
                            writer.WriteProcessingInstruction(reader.Name, reader.Value);
                            break;

                        case XmlNodeType.DocumentType:
                            writer.WriteDocType(
                                reader.Name,
                                reader.GetAttribute("PUBLIC"),
                                reader.GetAttribute("SYSTEM"),
                                string.IsNullOrEmpty(reader.Value) ? null : reader.Value);
                            break;

                        case XmlNodeType.EntityReference:
                            writer.WriteEntityRef(reader.Name);
                            break;

                        // Whitespace inside xml:space="preserve" is part of the content.
                        case XmlNodeType.SignificantWhitespace:
                            writer.WriteWhitespace(reader.Value);
                            break;
                    }
                }
            }
        }
        catch (XmlException ex)
        {
            return OperationResult<XmlFormatResult>.Fail(new ToolError(
                Clean(ex.Message), ex.LineNumber > 0 ? ex.LineNumber : null, ex.LinePosition > 0 ? ex.LinePosition : null));
        }

        var output = declaration is null
            ? body.ToString()
            : opts.Minify ? declaration + body : declaration + "\n" + body;

        return OperationResult<XmlFormatResult>.Ok(new XmlFormatResult(output, elements, attributes, maxDepth));
    }

    /// <summary>True when the text parses as a well-formed XML document.</summary>
    public static bool IsWellFormed(string? xml)
    {
        if (TextUtil.IsBlank(xml))
        {
            return false;
        }

        try
        {
            using var reader = XmlReader.Create(
                new StringReader(TextUtil.StripBom(xml).Trim()),
                new XmlReaderSettings { DtdProcessing = DtdProcessing.Ignore, XmlResolver = null });

            while (reader.Read())
            {
            }

            return true;
        }
        catch (XmlException)
        {
            return false;
        }
    }

    /// <summary>The reader's messages end with "Line 3, position 7." — the banner shows that separately.</summary>
    private static string Clean(string message)
    {
        var at = message.LastIndexOf(" Line ", StringComparison.Ordinal);
        return at > 0 ? message[..at].TrimEnd() : message;
    }
}
